cat-in-136/cargo-generate-rpm

src/error.rs
* Clarify Cargo.toml error in the error message
* Fix error message bug where "X of Y-th asset is undefined" should be displayed but actually "Y of X-th asset is undefined"
=> Fix error message

Cargo.toml, README.md, src/auto_req/builtin.rs, src/build_target.rs, src/config.rs, src/file_info.rs, src/main.rs
Using cargo build with cross-compilation, the built binary files are placed in `target/<target-triple>/release`, not usual `target/release`.  The location of the asset source should be automatically corrected in this case. The RPM files should also follow this rule.
In addition, `--target-dir` should be support to change the `target` folder path.
close #13
=> Support cross compile with `--target-dir` and `--target`

Cargo.toml
The latest revision of rpm-rs fixes this problem. But it is not pushed to crate.io. So git revision is specified in Cargo.toml.
In addition, update cargo_toml
to fix #21
=> Fix build fail on rust 1.53

Cargo.toml, src/config.rs, src/error.rs, src/file_info.rs
- Update rpm crate's version
- Add glob crate
- Add errors specific to globs
- Add glob detection and handling for assets
Glob support was already in cargo-deb and I wanted to have it in this crate, too. I added it for my own build, but I thought I'd share upstream. Please let me know if you'd like any changes at all. I could even feature gate it if you'd rather.
Thank you for the great crate, once again!
=> Add glob capability to assets

Cargo.toml, src/config/mod.rs, src/main.rs
Since `rpm-rs/rpm` is maintained, I'd suggest to address https://github.com/cat-in-136/cargo-generate-rpm/issues/20 to move over.
The first alpha release is pending a signoff https://github.com/rpm-rs/rpm/pull/73 .
Ref #39
TODO
=> chore: switch to maintained fork of rpm-rs, rpm-rs/rpm

Cargo.toml, README.md, src/config/metadata.rs, src/config/mod.rs, src/main.rs
`/bin/sh` is the package dependency which is not necessarily required if there is no (un)install script or script assets. This PR introduces a new configuration `package.metadata.generate-rpm.require-sh` to create packages not depending on `/bin/sh`.
to resolve #39
=> Support for rpm file which does not have a dependency on /bin/sh

README.md, src/config/file_info.rs, src/config/mod.rs
=> fix bug (#37) of glob in assets in combination with a workspace project and support for #50 directory target of non-glob assets

README.md, src/config/mod.rs
Tested locally to generate an rpm with vendor and repository both in `[package]` and `[package.metadata.generate-rpm]` in Cargo.toml
=> Add optional fields repository and vendor

README.md, src/config/mod.rs
#54 introduced package.metadata.generate-rpm.repository to specify URL of the rpm file. But, "URL" is intended to store the URL of the package home page, not the repository URL. So, package.metadata.generate-rpm.repository should be renamed to package.metadata.generate-rpm.url.
Due to same reason, its fallback should be "package.homepage". package.repository should be also used for second fallback when neither package.metadata.generate-rpm.url nor package.homepage exists. Because today there is many projects where package.repository present but package.url not present.
=> Rename package.metadata.generate-rpm.repository to url

README.md
Found via `typos --format brief`.
=> Fix typo, `buitin` -> `builtin`

src/config/mod.rs
`std::mem::transmute_copy` causes undefined behavior if the destination type and target type has different sizes. This PR eliminates this issue by using raw pointer to the data and converting it to a `u8` slice with the given size.
More detailed explanation: https://stackoverflow.com/questions/25917260/getting-raw-bytes-from-packed-struct
Fixes #62
=> Use raw pointer for `Dependency` to `u8` slice conversion

.github/workflows/rust.yml
This PR updates the continuous integration workflow to always build with `--locked` flag for making sure that `Cargo.lock` is up-to-date.
It will help spotting issues like bumping the version in `Cargo.toml` but not in `Cargo.lock` which is common for Rust projects.
=> Build with `--locked` flag during CI

.github/workflows/rust.yml, src/config/mod.rs
The https://github.com/cat-in-136/cargo-generate-rpm/pull/63 PR needs to be reviewed and addressed again.
Compareing Dependency using unsafe code is not good and causes compile errors. Also, the source code is simple and unlikely to have bugs, and there is no need to change it in the future. Therefore, we give up on unit test to check the problem areas.
=> backout #63 and give up compareing Dependency in the unit test code

src/main.rs
This PR adds `-V` flag for printing the version information of `cargo-generate-rpm`.
=> Add version flag

README.md, src/build_target.rs, src/config/file_info.rs, src/main.rs
When expanding an asset path, currently only the "target/release/" prefix could be remapped. By comprehending the build profile, path expansion can happen for "target/<profile>". This enables use of both alternative target-triple and build profiles.
For example, given the following asset configuration in Cargo.toml:
[package.metadata.generate-rpm]
assets = [
{ source = "target/my-profile/my-exe", dest = "/usr/bin/", mode = "755" },
]
rpms can be generated for multiple target triples, such as:
cargo generate-rpm --profile my-profile --target x86_64-unknown-linux-musl
cargo generate-rpm --profile my-profile --target i668-unknown-linux-musl
with the paths for the "my-exe" executable expanded correctly to:
target/x86_64-unknown-linux-musl/my-profile/my-exe …
=> Add --profile command line option

src/config/file_info.rs
When `--target` specified and the asset file of rust artifact does not exist, the error message should contain the expanded path such as: `target/my-target/program_name`, but actually contains the original path: `target/release/program_name`
=> Fixed warning displayed for file paths before expansion when `--target` and `--profile` options specified and the file does not exist.

README.md
`cargo-generate-rpm` currently relies on the `rpm` crate, while readme links the older `rpm-rs` crate.
=> Replace `rpm-rs` with `rpm` in readme

Cargo.toml, src/config/mod.rs, src/main.rs
Reverts cat-in-136/cargo-generate-rpm#75 and bump rpm to v0.11.0 because of regrade for none compression type feature
Details is written in https://github.com/cat-in-136/cargo-generate-rpm/commit/dc6b4c6ee3940d8b4b8d8df75b7530c10b0fb671#r114846727
=> Revert rpm crate back to v0.9.0-alpha.1

src/config/mod.rs
The find requires logic should be passed the files that have already had profile/target directory mapping logic applied, otherwise ldd/find-requires won't find the files.
fixes: https://github.com/cat-in-136/cargo-generate-rpm/issues/77
=> use expanded file list when determining reqs

src/config/file_info.rs
#73 does not take care special case that `--profile dev` refer to `target/debug` not  `target/deb`. This PR resolve this special case.
=> target path for `--profile dev` refer to `target/debug/foobar`

Cargo.toml, src/config/mod.rs, src/error.rs, src/main.rs
upgrade to rpm crates and removing pgp dependency.
Rework of #75, which was reverted in #76. This PR take into account of breaking change of rpm-rs crate mentioned by @dralley in https://github.com/cat-in-136/cargo-generate-rpm/commit/dc6b4c6ee3940d8b4b8d8df75b7530c10b0fb671#r114846727.
This PR also remove pgp dependency. Because it is not used by cargo-generate-rpm as of now. This also resolve #84.
=> upgrade rpm crates (v0.11)

Cargo.toml, src/auto_req/builtin.rs, src/auto_req/mod.rs, src/auto_req/script.rs, src/build_target.rs, src/cli.rs, src/config/file_info.rs, src/config/metadata.rs, src/config/mod.rs, src/error.rs, src/main.rs
While `clap`-based code is somewhat heavier than `getopts`, it's more powerful and results in cleaner and easier to maintain code.
This PR also fixes a bunch of Clippy warnings and introduces the `source-date` flag necessary for reproducible builds.
I am not completely sure I got the extra metadata stuff correctly, so it's better to double check it.
Closes #82
=> Update rpm, migrate to clap and add source_date_epoch flag

src/main.rs
Fixup bug from clap migration where the target file name was determined using the `target` argument and the docs indicate that it should be determined using the `output` argument.
=> Output directory now used by target_file_name

README.md, src/config/file_info.rs, src/config/mod.rs
This is an attempt to resolve issue 86. This way if the script is a path, we can load that into the RPM instead of relying on installing the script manually.
=> If the scripts happen to be paths that exist load them

Cargo.toml, README.md, src/config/file_info.rs, src/config/metadata.rs, src/error.rs, src/main.rs
Add support for setting capabilities on assets. 
Exposing functionality added to rpm-rs in this PR, https://github.com/rpm-rs/rpm/pull/166
=> Add support for capabilities

src/cli.rs
Adding a  `no` alias to auto-req for the `disabled` option to reverse a regression made as part of #82 see #101 for details.
```
> #before 
> cargo run --release -- --auto-req no
error: invalid value 'no' for '--auto-req <AUTO_REQ>'
[possible values: disabled, builtin, find-requires, /path/to/find-requires]
For more information, try '--help'.
> #after
> cargo run --release -- --auto-req no
>
```
=> add alias to auto_req for disabled option

README.md, src/config/file_info.rs
introduce `config = "noreplace"` to file information so that the file is not be replaced on the installation as like `%config(noreplaced)` specified in the RPM spec file.
to close #88.
=> add support for config noreplace

Cargo.toml, README.md, src/auto_req/mod.rs, src/cli.rs, src/config/mod.rs
Fix the following issues caused by clap migration (#83)
- `--auto-req auto` does not work
- `--auto-req /path/to/find-requires` does not work (fix #107)
This PR also contains:
- Add `disabled` description to README.md
- Add `find-requires` description to README.md
- Add some test codes
=> Fix degrades of `--auto-req` caused by clap migration (#83)

README.md, src/cli.rs, src/config/metadata.rs, src/config/mod.rs, src/main.rs
to fix #109
* take consideration into the argument order among --metadata-overwrite, --set-metadata(-s) and --variant
* remove value_delimiter = ',' from  --set-metadata(-s) so that it can handle array and hash
* add some test codes
* update README.md
=> fix metadata overwrite option behaviour due to clap degression

Cargo.toml, README.md, src/config/file_info.rs, src/config/mod.rs
Upgrade dependency library versions. This includes upgrading to rpm-rs so that RPMv3 is no longer supported i.e., which is to close #106.
=> Upgrade crates

.github/workflows/rust.yml, src/cli.rs
=> Fix #114 degrade bug where running as a cargo subcommand raise an error

src/cli.rs
Fixes #118. 
Expect this issue can be fixed in multiple ways and happy for an alternative to be suggested. The underlying issue is that we're not correctly parsing the argument matches when cargo-generate-rpm is called as a cargo subcommand. 
To regain the previous behaviour the arguments of the `generate-rpm` subcommand need to be reparsed. The issue can be reproduced by running `cargo run generate-rpm` on the latest main. 
```
thread 'main' panicked at src/cli.rs:134:40:
`"metadata_overwrite"` is not an id of an argument or a group.
```
=> Fixup cli to handle parsing matches when called as a cargo subcommand

src/auto_req/script.rs
The empty-package dependency  (empty line on `rpm -qpR output.rpm`)  was added under the following conditions:
- script-based (`/usr/lib/rpm/find-requires`) automatic dependency processing is used; and
- all the assets have no dependencies (e.g., non-executable files)
This PR fixes it and now correctly adds no dependency line.
to close #131
=> Fix bug where empty dependency was added to package in case of no dependency

Cargo.toml, src/cli.rs, src/error.rs
This pull request selectively cherry-picks only the following changes from pull request #133. In addition, bump rust edition to 2024.
> Dependency updates and improvements:
> 
> * [`Cargo.toml`](https://github.com/cat-in-136/cargo-generate-rpm/pull/133/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L16-R30): Updated the `rpm` crate to version 0.17 and added several compression features. Updated versions for `cargo_toml`, `clap`, and `thiserror` crates.
> 
> Minor fixes:
> 
> * [`Cargo.toml`](https://github.com/cat-in-136/cargo-generate-rpm/pull/133/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L5-R9): Reformatted the `categories` and `assets` sections for better readability. …
=> Update crates and bump rust edition to 2024

Cargo.toml, README.md, src/cli.rs, src/main.rs
Adds a CLI option to sign the packaged RPM with a provided key
Adds the `signature-pgp` feature to the `rpm` dependency
Closes #139
=> Add option to supply PGP signing key
